/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppBibliotecaRouteImport } from './routes/app/biblioteca'
import { Route as AppConfiguracoesRouteImport } from './routes/app/configuracoes'
import { Route as AppCriarRouteImport } from './routes/app/criar'
import { Route as AppResultadosRouteImport } from './routes/app/resultados'
import { Route as JogarIndexRouteImport } from './routes/jogar/index'
import { Route as JogarCodigoRouteImport } from './routes/jogar/$codigo'
import { Route as AppAtividadeIdRouteImport } from './routes/app/atividade/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBibliotecaRoute = AppBibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCriarRoute = AppCriarRouteImport.update({
  id: '/criar',
  path: '/criar',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppResultadosRoute = AppResultadosRouteImport.update({
  id: '/resultados',
  path: '/resultados',
  getParentRoute: () => AppRouteRoute,
} as any)
const JogarIndexRoute = JogarIndexRouteImport.update({
  id: '/jogar/',
  path: '/jogar/',
  getParentRoute: () => rootRouteImport,
} as any)
const JogarCodigoRoute = JogarCodigoRouteImport.update({
  id: '/jogar/$codigo',
  path: '/jogar/$codigo',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAtividadeIdRoute = AppAtividadeIdRouteImport.update({
  id: '/atividade/$id',
  path: '/atividade/$id',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/app/biblioteca': typeof AppBibliotecaRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/criar': typeof AppCriarRoute
  '/app/resultados': typeof AppResultadosRoute
  '/jogar/$codigo': typeof JogarCodigoRoute
  '/app/': typeof AppIndexRoute
  '/jogar/': typeof JogarIndexRoute
  '/app/atividade/$id': typeof AppAtividadeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/app/biblioteca': typeof AppBibliotecaRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/criar': typeof AppCriarRoute
  '/app/resultados': typeof AppResultadosRoute
  '/jogar/$codigo': typeof JogarCodigoRoute
  '/app': typeof AppIndexRoute
  '/jogar': typeof JogarIndexRoute
  '/app/atividade/$id': typeof AppAtividadeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/app/biblioteca': typeof AppBibliotecaRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/criar': typeof AppCriarRoute
  '/app/resultados': typeof AppResultadosRoute
  '/jogar/$codigo': typeof JogarCodigoRoute
  '/app/': typeof AppIndexRoute
  '/jogar/': typeof JogarIndexRoute
  '/app/atividade/$id': typeof AppAtividadeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/cadastro'
    | '/login'
    | '/app/biblioteca'
    | '/app/configuracoes'
    | '/app/criar'
    | '/app/resultados'
    | '/jogar/$codigo'
    | '/app/'
    | '/jogar/'
    | '/app/atividade/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/login'
    | '/app/biblioteca'
    | '/app/configuracoes'
    | '/app/criar'
    | '/app/resultados'
    | '/jogar/$codigo'
    | '/app'
    | '/jogar'
    | '/app/atividade/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/cadastro'
    | '/login'
    | '/app/biblioteca'
    | '/app/configuracoes'
    | '/app/criar'
    | '/app/resultados'
    | '/jogar/$codigo'
    | '/app/'
    | '/jogar/'
    | '/app/atividade/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  JogarCodigoRoute: typeof JogarCodigoRoute
  JogarIndexRoute: typeof JogarIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/biblioteca': {
      id: '/app/biblioteca'
      path: '/biblioteca'
      fullPath: '/app/biblioteca'
      preLoaderRoute: typeof AppBibliotecaRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/criar': {
      id: '/app/criar'
      path: '/criar'
      fullPath: '/app/criar'
      preLoaderRoute: typeof AppCriarRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/resultados': {
      id: '/app/resultados'
      path: '/resultados'
      fullPath: '/app/resultados'
      preLoaderRoute: typeof AppResultadosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/jogar/': {
      id: '/jogar/'
      path: '/jogar'
      fullPath: '/jogar/'
      preLoaderRoute: typeof JogarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogar/$codigo': {
      id: '/jogar/$codigo'
      path: '/jogar/$codigo'
      fullPath: '/jogar/$codigo'
      preLoaderRoute: typeof JogarCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/atividade/$id': {
      id: '/app/atividade/$id'
      path: '/atividade/$id'
      fullPath: '/app/atividade/$id'
      preLoaderRoute: typeof AppAtividadeIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppBibliotecaRoute: typeof AppBibliotecaRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppCriarRoute: typeof AppCriarRoute
  AppResultadosRoute: typeof AppResultadosRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAtividadeIdRoute: typeof AppAtividadeIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppBibliotecaRoute: AppBibliotecaRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppCriarRoute: AppCriarRoute,
  AppResultadosRoute: AppResultadosRoute,
  AppIndexRoute: AppIndexRoute,
  AppAtividadeIdRoute: AppAtividadeIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  JogarCodigoRoute: JogarCodigoRoute,
  JogarIndexRoute: JogarIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
